- name: Install cerbot and obatin SSL cert BLOCK
  block:
  - name: Intall pip
    apt:
      pkg:
        - pip
        - python3-venv
        - python3-virtualenv
      state: latest
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: Intall pip
    dnf:
      pkg:
        - pip
        - python3-pytest-venv
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Create certbot dir
    file:
      path: /opt/certbot/
      state: directory

  - name: Setup pip env and install certbot
    pip:
      name:
        - certbot
        - certbot_dns_porkbun
      virtualenv: /opt/certbot/
      state: latest

  - name: Obtain certificate with certbot
    shell: '/opt/certbot/bin/certbot certonly \
    --non-interactive \
    --agree-tos \
    --email {{ email_address }} \
    --preferred-challenges dns \
    --authenticator dns-porkbun \
    --dns-porkbun-key {{ porkbun_api_key }} \
    --dns-porkbun-secret {{ porkbun_secret }} \
    --dns-porkbun-propagation-seconds 60 \
    -d "*.{{ domain_name }}"'
    register: shell_cert
  when: envoy is defined
