- name: Install fail2ban for debian based system
  apt:
    pkg: fail2ban
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"


- name: Install fail2ban for RHEL based system
  dnf:
    pkg: fail2ban
    state: latest
  when: ansible_distribution == "Fedora"

- name: Copy basic config for fail2ban
  copy:
    src: ./easy_envoy/files/jail.local
    dest: /etc/fail2ban/jail.d/jail.local
  notify: start_fail2ban
