- name: Install UFW and set rules for debian based system
  block:
  - name: Install UFW
    apt:
      pkg: ufw
      state: latest

  - name: Allow ssh rules
    ufw:
      rule: allow
      to_port: '22'
      proto: tcp
      state: reloaded

  - name: Allow hhtp rules
    ufw:
      rule: allow
      to_port: '80'
      state: reloaded

  - name: Allow hhtps rules
    ufw:
      rule: allow
      to_port: '443'
      state: reloaded

  - name: Allow internal traffic
    ufw:
      rule: allow
      from_ip: '10.1.0.0/8'
      state: reloaded

  - name: Allow internal traffic
    ufw:
      rule: allow
      from_ip: '172.16.0.0/16'
      state: reloaded

  - name: Allow internal traffic
    ufw:
      rule: allow
      from_ip: '192.168.0.0/16'
      state: reloaded

  - name: Deny policy
    ufw:
      default: deny
      state: enabled
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"


- name: Install firewalld and set rules for RHEL based system BLOCK
  block:
  - name: Install firewalld
    dnf:
      pkg: firewalld
      state: latest
  - name: Allow ssh rule for public
    ansible.posix.firewalld:
      service: ssh
      offline: True
      permanent: true
      state: enabled
  - name: Drop all incoming traffic in default(public) zone
    ansible.posix.firewalld:
      zone: public
      target: DROP
      permanent: true
      state: present
  - name: Allow all internal traffic '10'
    ansible.posix.firewalld:
      source: '10.1.0.0/8'
      zone: internal
      permanent: true
      offline: True
      state: enabled
  - name: Allow all internal traffic '172'
    ansible.posix.firewalld:
      source: '172.16.0.0/16'
      zone: internal
      offline: True
      permanent: true
      state: enabled
  - name: Allow all internal traffic ports
    ansible.posix.firewalld:
      port: '22-9999/tcp'
      zone: internal
      offline: True
      permanent: true
      state: enabled
  - name: Enable firewalld daemon
    systemd:
      name: firewalld
      state: started
      enabled: True
  - name: Reload firewalld config
    shell: firewall-cmd --reload
  when: ansible_distribution == "Fedora"



