- name: Install prometheus BLOCK
  block:
  - name: Get Prometheus archive
    get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v3.0.0/prometheus-3.0.0.linux-amd64.tar.gz
      dest: /root/

  - name: Create user for prometheus
    user:
      name: prometheus
      shell: /bin/nologin
      state: present

  - name: Create dir for Prometheus
    file:
      path: /opt/prometheus/
      state: directory

  - name: Unpack Prometheus archive
    unarchive:
      src: /root/prometheus-3.0.0.linux-amd64.tar.gz
      remote_src: True
      dest: /opt/prometheus/
      owner: prometheus

  - name: Create prometheus config
    template:
      src: ./easy_envoy/templates/prometheus.yml.j2
      dest: /etc/prometheus.yml

  - name: Copy systemd service unit file
    copy:
      src: ./easy_envoy/files/prometheus.service
      dest: /etc/systemd/system/prometheus.service
    notify: start_prometheus
  when: prometheus is defined


