- name: Install vnc server BLOCK
  block:
  - name: Install vnc server
    apt:
      pkg:
        - tigervnc-standalone-server
        - dbus-x11
      state: latest
    when: ansible_distribution != "Fedora"

  - name: Install vnc server
    dnf:
      pkg: tigervnc-common
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Copy vnc server config
    copy:
      src: ./easy_envoy/files/vncserver-config-defaults
      dest: /etc/tigervnc/vncserver-config-defaults
    when: ansible_distribution == "Fedora"

  - name: Copy vnc server user list
    copy:
      src: ./easy_envoy/files/vncserver.users
      dest: /etc/tigervnc/vncserver.users

  - name: Create vnc user
    user:
      name: vnc_user

  - name: Put vncserver service file
    copy:
      src: ./easy_envoy/files/ubuntu_vncserver@.service
      dest: /etc/systemd/system/vncserver@.service
    notify:
      - vncserver_start
    when: ansible_distribution == "Ubuntu"

  - name: Put vncserver service file
    copy:
      src: ./easy_envoy/files/ubuntu_vncserver@.service
      dest: /etc/systemd/system/vncserver@.service
    notify:
      - vncserver_start
    when: ansible_distribution == "Debian"


  - name: Put vncserver service file
    copy:
      src: ./easy_envoy/files/vncserver@.service
      dest: /etc/systemd/system/vncserver@.service
    notify:
      - vncserver_start
    when: ansible_distribution == "Fedora"
  when: vnc_server is defined


