- name: Install wastebin BLOCK
  block:
  - name: Get wastebin binary archive
    get_url:
      url: https://github.com/matze/wastebin/releases/download/2.5.0/wastebin_2.5.0_x86_64-unknown-linux-musl.tar.zst
      dest: /root/

  - name: Create wastebin dir
    file:
      path: /opt/wastebin
      state: directory
  - name: Create vscode dir
    file:
      path: /var/local/envoy/
      mode: '1777'
      state: directory



  - name: Unpack wastebin archive
    unarchive:
      src: /root/wastebin_2.5.0_x86_64-unknown-linux-musl.tar.zst
      remote_src: True
      dest: /opt/wastebin/

  - name: Create user for wastebin
    user:
      name: wastebin
      shell: /bin/nologin
      state: present
      system: False

  - name: Copy systemd unit file for wastebin
    copy:
      src:  ./easy_envoy/files/wastebin.service
      dest: /etc/systemd/system/wastebin.service
    notify:
      - wastebin_start
  when: wastebin is defined


